CUISINE_TO_REGION = {
    # --- ASIAN & PACIFIC ---
    "Afghani": "Middle East & Central Asia",
    "Asian": "Asia (General)",
    "Australian": "Oceania",
    "Beijing cuisine": "East Asia",
    "Central Asian": "Middle East & Central Asia",
    "Chinese": "East Asia",
    "Indian": "South Asia",
    "Japanese": "East Asia",
    "Japanese Fusion": "East Asia",
    "Japanese sweets parlour": "East Asia",
    "Korean": "East Asia",
    "Malaysian": "Southeast Asia",
    "Mongolian": "East Asia",
    "Nepalese": "South Asia",
    "Pakistani": "South Asia",
    "Polynesian": "Oceania",
    "Sri Lankan": "South Asia",
    "Taiwanese": "East Asia",
    "Thai": "Southeast Asia",
    "Uzbek": "Middle East & Central Asia",
    "Vietnamese": "Southeast Asia",
    "Xinjiang": "East Asia",

    # --- EUROPEAN (REGIONAL & MACRO) ---
    "Albanian": "Eastern Europe",
    "Austrian": "Central Europe",
    "Balti": "United Kingdom (British-Asian)",
    "Belgian": "Western Europe",
    "British": "Western Europe",
    "Central European": "Central Europe",
    "Croatian": "Eastern Europe",
    "Czech": "Central Europe",
    "Danish": "Northern Europe",
    "Eastern European": "Eastern Europe",
    "European": "Europe (General)",
    "French": "Western Europe",
    "German": "Central Europe",
    "Greek": "Mediterranean",
    "Hungarian": "Central Europe",
    "Irish": "Western Europe",
    "Mediterranean": "Mediterranean",
    "Norwegian": "Northern Europe",
    "Polish": "Central Europe",
    "Portuguese": "Southern Europe",
    "Romanian": "Eastern Europe",
    "Russian": "Eastern Europe",
    "Scandinavian": "Northern Europe",
    "Spanish": "Southern Europe",
    "Swiss": "Central Europe",

    # --- THE ITALIAN REGIONAL BREAKDOWN (Crucial for deep semantics) ---
    "Calabrian": "Southern Italy",
    "Campania": "Southern Italy",
    "Central-Italian": "Central Italy",
    "Emilian": "Northern Italy",
    "Italian": "Italy (General)",
    "Lazio": "Central Italy",
    "Lombard": "Northern Italy",
    "Neapolitan": "Southern Italy",
    "Northern-Italian": "Northern Italy",
    "Romana": "Central Italy",
    "Sardinian": "Islands Italy",
    "Sicilian": "Islands Italy",
    "Southern-Italian": "Southern Italy",
    "Tuscan": "Central Italy",

    # --- AMERICAS ---
    "American": "North America",
    "Argentinian": "South America",
    "Brazilian": "South America",
    "Cajun & Creole": "North America",
    "Caribbean": "Caribbean",
    "Central American": "Central America",
    "Colombian": "South America",
    "Hawaiian": "North America",
    "Latin": "Latin America",
    "Mexican": "Central America",
    "Native American": "North America",
    "Peruvian": "South America",
    "South American": "South America",
    "Southwestern": "North America",
    "Venezuelan": "South America",

    # --- MIDDLE EAST & AFRICA ---
    "African": "Africa (General)",
    "Arabic": "Middle East",
    "Egyptian": "North Africa",
    "Ethiopian": "East Africa",
    "Israeli": "Middle East",
    "Lebanese": "Middle East",
    "Middle Eastern": "Middle East",
    "Moroccan": "North Africa",
    "Nigerian": "West Africa",
    "Persian": "Middle East",
    "Tunisian": "North Africa",
    "Turkish": "Middle East & Mediterranean",

    
}

ESTABLISHMENT_FORMATS = {
    # --- ESTABLISHMENT FORMATS & FOOD TYPES ---
    "Bar": "Drinking & Nightlife",
    "Barbecue": "Grill & BBQ",
    "Beer restaurants": "Drinking & Nightlife",
    "Brew Pub": "Drinking & Nightlife",
    "Cafe": "Cafe & Desserts",
    "Contemporary": "Modern Dining",
    "Deli": "Quick Bites",
    "Diner": "Casual Dining",
    "Dining bars": "Drinking & Nightlife",
    "Fast food": "Quick Bites",
    "Fruit parlours": "Cafe & Desserts",
    "Fusion": "Modern Dining",
    "Gastropub": "Drinking & Nightlife",
    "Grill": "Grill & BBQ",
    "Healthy": "Specialty Focus",
    "International": "Global",
    "Pizza": "Pizza & Pasta",
    "Pub": "Drinking & Nightlife",
    "Seafood": "Specialty Focus",
    "Soups": "Casual Dining",
    "Steakhouse": "Grill & BBQ",
    "Street Food": "Quick Bites",
    "Sushi": "Specialty Focus",
    "Wine Bar": "Drinking & Nightlife"
}